backend:
  name: github
  repo: TON_UTILISATEUR_GITHUB/TON_REPO # Modifie avec ton user et repo GitHub
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content.json"
        label: "Contenu de la page d'accueil"
        name: "homepage"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "text"}
