backend:
  name: github
  repo: Bateau07/Journal_Bateau
  branch: main

  # Ajoute ceci :
  site_domain: journalbateau.netlify.app

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content.json"
        label: "Contenu"
        name: "home"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte", name: "body", widget: "text" }
